### ISSUE TITLE
no releases for 0.10.0 (since 20170527)??

### ISSUE THREAD

**Issue by Pagey** [yajiedesign/mxnet#11]
no pre-compiled releases in10 days, since dmlc/mxnet released 0.10.0? any plan to return releases (will be most welcome!!)

Thanks M

PS if compatible cudnn versions etc. could be updated to newest versions it would also be great

**Comment by yajiedesign** [comment]
thanks .it fixed now

**Comment by Pagey** [comment]
thanks dearly. does the build depend on cuDNN v5.1 or should it work with cuDNN v6.0?

**Comment by Pagey** [comment]
nope seems to require v5.1..

**Comment by yajiedesign** [comment]
@Pagey v5.1
