### ISSUE TITLE
Running mxnet in CPU only mode

### ISSUE THREAD

**Issue by santanpereira** [yajiedesign/mxnet#18]
I am trying to run 20170907_mxnet_x64_vc14_cpu.7z mxnet release in https://github.com/msracver/Deformable-ConvNets project demos in cpu-only mode on  Windows Server 2016 Standard and running into this error ... 
[02:05:01] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\src\operator\contrib\./n‌​n/deformable_im2col.‌​h:113: only implemented in GPU.

Everything works for me in GPU mode. Can someone please help me how to go about making it run on CPU only mode. What all changes will I need to make to achieve this?

**Comment by santanp** [comment]
Thanks, figured out the issue to get rid of the error. Had to implement the operators for CPU.

**Comment by santanpereira** [comment]
Thanks, figured out the issue to get rid of the error. Had to implement the operators for CPU.

**Comment by yajiedesign** [comment]
yes.this op not cpu implemented,you can build issue in https://github.com/apache/incubator-mxnet and wait it or do it you self.thanks.
