### ISSUE TITLE
Could you please provide a tutorial about how to compile mxnet with cpp package on win10?

### ISSUE THREAD

**Issue by EternalSaga** [yajiedesign/mxnet#26]
I tried to compile mxnet with cpp package on win10, vs2015 for many times, but I have never succeed.  Could you please provide a tutorial about building mxnet with cpp package, opencv, and cuda on windows?

There are a large amount of errors in cuda header files such as:
Severity	Code	Description	Project	File	Line	Suppression State
Error		expected an identifier	mxnet	C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include\thrust\system\cuda\detail\core\util.h	761

**Comment by visionNoob** [comment]
@EternalSaga did you solve this issue?

**Comment by EternalSaga** [comment]
> 
> 
> @EternalSaga did you solve this issue?

You can refer to this issue post by me. [](https://github.com/apache/incubator-mxnet/issues/10049)

**Comment by visionNoob** [comment]
@EternalSaga oh. thank you. It is so helpful for me! 
Can i ask one more question?
 Is new "include" folder created during building mxnet?
I successfully build libmxnet.lib and dll (i sovled op.h problem individually), but 
no "include" folder was made. 
Should I construct include folder manually?

**Comment by EternalSaga** [comment]
> 
> 
> @EternalSaga oh. thank you. It is so helpful for me!
> Can i ask one more question?
> Is new "include" folder created during building mxnet?
> I successfully build libmxnet.lib and dll (i sovled op.h problem individually), but
> no "include" folder was made.
> Should I construct include folder manually?

The headers are generated by the OpWrapperGenerator.py script in mxnet.

**Comment by liuchanfeng165** [comment]
> @EternalSaga oh. thank you. It is so helpful for me!
> Can i ask one more question?
> Is new "include" folder created during building mxnet?
> I successfully build libmxnet.lib and dll (i sovled op.h problem individually), but
> no "include" folder was made.
> Should I construct include folder manually?

Hi ,@visionNoob ,How to solve this problem ? 
line 761 is 'enum {SIZE = N};'.
