### ISSUE TITLE
Inclusion of 3rd party headers

### ISSUE THREAD

**Issue by jeremiedb** [yajiedesign/mxnet#28]
It appears that since the March 30th built, the header files for DMLC, NNVM and MSHADOW are now longer included in the build, for example in: `20180330_mxnet_x64_vc14_cpu.7z`. 
Those headers are needed when building the R-package, so maintain their inclusion would be helpful in keeping the update process simple. 
Thanks!

**Comment by yajiedesign** [comment]
I will adjust the build settings
