### ISSUE TITLE
Fail to load libmxnet.dll since 2018-05-08

### ISSUE THREAD

**Issue by jeremiedb** [yajiedesign/mxnet#29]
Hi, the building of the R package started failing since the 2018-05-08 built. 
The libmxnet.dll cannot be loaded, which might be due to a change in the underlying libraries. Are you aware of any change in third party libraries around May 9th that could explain this? 

Thanks!

**Comment by yajiedesign** [comment]
some pr borken sicne 2018-5-8. i will fixed ot asap

**Comment by yajiedesign** [comment]
fixed done,please test.

**Comment by jeremiedb** [comment]
Just compiled on 2018-06-14 built and it works fine. Thanks!
