### ISSUE TITLE
Why is there release bag here?

### ISSUE THREAD

**Issue by lightningsoon** [yajiedesign/mxnet#4]
Thank you for your help.I have built source code for hours and met many errors.

**Comment by yajiedesign** [comment]
> Why is there release bag here

what you means ?
what error?need more info. and please send issue to https://github.com/dmlc/mxnet/issues

**Comment by lightningsoon** [comment]
test following code
`
import mxnet as mx 
a = mx.nd.ones(1) 
b = mx.nd.ones(1,mx.gpu()) 
a.asnumpy()
==> array([ 1.], dtype=float32)
b.asnumpy()
==>array([ 0.], dtype=float32)
`
It may not use gpu according this 
[url](http://www.voidcn.com/blog/u010414386/article/p-6319697.html)
the comment was throw by me.

**Comment by yajiedesign** [comment]
copy you cudnn to cuda.
cudnn64_5.dll to bin
cudnn.lib to lib\x64

**Comment by lightningsoon** [comment]
I'm coming.
I have moven content contained in mxnet\3rdparty\cudnn to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0.
I also try copy things from F:\cudnn-8.0-windows10-x64-v5.1\cuda to there.
But result was not changed.

I guess I didn't understand your mean.

**Comment by lightningsoon** [comment]
Why do you publish a windows release nightly?
Could you please provide **badduyun's or onedrive's**  links?
Thank you very much!

**Comment by lightningsoon** [comment]
download the latest package.
you can finish installing succefully!
