### ISSUE TITLE
MXNet Reference Error (Pyhton System Error) due to cudnn64_5.dll referenced in MXNet 0.9.4 package

### ISSUE THREAD

**Issue by CarminaBurana** [yajiedesign/mxnet#5]
Hi,

I am new to this. Tried to install your Pre-Packaged Nightly Build 0.9.4 from this location: 
https://github.com/yajiedesign/mxnet/releases/download/20170220/20170220_mxnet_x64_vc14_gpu.7z 
MXNet installation went fine. I can see the cudnn64_70.dll under mxnet\3rdparty\cudnn folder.

At runtime though, python cannot load libmxnet.net because of a reference to cudnn64_5.dll.
I checked libmxnet.dll coming with the build 0.9.4 and I can see a reference to symbol cudnnSpatialTfGridGeneratorBackward expected to come with cudnn64_5.dll which is not specific to this build.

What am I missing please (besides cudnn64_5.dll)?
Please see error details below.

Thank you very much!

## Environment info
Operating System: Windows 7 Professional
Compiler: Visual Studio Community 2015
Environment: Anaconda 3
Package used: Python
MXNet version: 0.9.3 / x64 / GPU Version
Python version and distribution: 3.5.2

## Error Message:

python.exe - System Error
The program can't start because cudnn64_5.dll is missing from your computer. Try re-installing the program to fix this problem.

## Minimum reproducible example

This happens when executing first statement (import mxnet) in README sample:
     >>> import mxnet as mx;
    >>> a = mx.nd.ones((2, 3));
    >>> print ((a*2).asnumpy());

**Comment by yajiedesign** [comment]
this prebuild and use cuda 8.0 and cudnn5.1 .
please use cudnn5.1 for cuda 8.0.

**Comment by CarminaBurana** [comment]
Thanks a lot! It worked great! 
Highly appreciate your help!
