### ISSUE TITLE
VC12 base prebuilt version

### ISSUE THREAD

**Issue by zwx8981** [yajiedesign/mxnet#6]
Hi, do you still plan to provide VC12 base prebuilt MXNET? It stops updating for a while.

**Comment by yajiedesign** [comment]
@zwx8981 the vc12 cannot compile now.

**Comment by zwx8981** [comment]
@yajiedesign Is this means that I must install a VS2015 for compiling the lastest version of MXNET?

**Comment by yajiedesign** [comment]
@zwx8981 yes

**Comment by zwx8981** [comment]
@yajiedesign OK, thank you.

**Comment by zwx8981** [comment]
@yajiedesign Hi, it seems that lastest version can not be downloaded successfully.
