### ISSUE TITLE
libmxnet.dll seems very big

### ISSUE THREAD

**Issue by hughsando** [yajiedesign/mxnet#7]
After downloading the nightlies (thank you very much for providing), I notice the libmxnet.dll is very large (250M):
 253384704 Mar 21 04:01 libmxnet.dll

Although, it does compress very small.  Is this correct?  Perhaps there is a lot of empty data in there, which I guess might make some sense.

**Comment by yajiedesign** [comment]
no problem.it is gpu code.

**Comment by hughsando** [comment]
Thanks for the information.
