### ISSUE TITLE
libmxnet.dll not updated since 20170323

### ISSUE THREAD

**Issue by jeremiedb** [yajiedesign/mxnet#9]
The last modified date on the latest releases for `lib/libmxnet.dll` is 20170323. 
Is this normal? 

There was a bug correction for making the R package work again around 20170306 but that correction is not in place when I build the package from the `20170408_mxnet_x64_vc14_cpu.7z`. 

Are the details of your receipe for Windows build available (Cmake options, c++ compiler, etc)? I can build the libmxnet.dll library from VS15, but mine crashes when building the R package.

**Comment by yajiedesign** [comment]
i will check

**Comment by yajiedesign** [comment]
ok,it some small mistake.you can find new dll in build path.

**Comment by jeremiedb** [comment]
It works! Thanks a lot for the fix.
